version: 0.2
phases:
  build:
    commands:
      - >
        sam build 
        --base-dir . 
        --template-file .aws/deploy/sam_template.yml
        
      - >
        sam deploy
        --stack-name hello-app 
        --capabilities CAPABILITY_IAM 
        --region ap-northeast-1 
        --s3-bucket codepipeline-ap-northeast-1-492472756923
        --parameter_overrides DeployEnv=DEV BuildGitHash=asgfs53
